# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-21 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectUploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='ObjectUploads/%Y-%m-%d/', verbose_name='ObjectUploads picture')),
                ('result', models.CharField(blank=True, max_length=200, null=True, verbose_name='Short Bio')),
            ],
        ),
    ]
