# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-21 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('whatinsideImage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectuploads',
            name='slug',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False),
        ),
    ]
